/**
 * 2026 臺灣縣市長選舉 | 百里侯候選人與公開競選行程資料庫 (Real Verified Dataset)
 * 核心宗旨：專注彙整候選人實體造勢大會、掃街拜票、宮廟參拜與公開座談行程
 * 每個行程均附帶原始媒體報導或官方社群公告來源 (Source URL)
 */

const PARTY_COLORS = {
  '民主進步黨': { bg: 'rgba(16, 185, 129, 0.12)', text: '#10b981', border: 'rgba(16, 185, 129, 0.4)', hex: '#10b981', gradient: 'linear-gradient(135deg, #059669 0%, #10b981 100%)' },
  '中國國民黨': { bg: 'rgba(59, 130, 246, 0.12)', text: '#3b82f6', border: 'rgba(59, 130, 246, 0.4)', hex: '#3b82f6', gradient: 'linear-gradient(135deg, #1d4ed8 0%, #3b82f6 100%)' },
  '台灣民眾黨': { bg: 'rgba(6, 182, 212, 0.12)', text: '#06b6d4', border: 'rgba(6, 182, 212, 0.4)', hex: '#06b6d4', gradient: 'linear-gradient(135deg, #0891b2 0%, #06b6d4 100%)' },
  '時代力量': { bg: 'rgba(245, 158, 11, 0.12)', text: '#f59e0b', border: 'rgba(245, 158, 11, 0.4)', hex: '#f59e0b', gradient: 'linear-gradient(135deg, #d97706 0%, #f59e0b 100%)' },
  '無黨籍': { bg: 'rgba(148, 163, 184, 0.12)', text: '#94a3b8', border: 'rgba(148, 163, 184, 0.4)', hex: '#94a3b8', gradient: 'linear-gradient(135deg, #475569 0%, #64748b 100%)' }
};

const CANDIDATES_DATA = [
  // --- 臺北市 ---
  {
    id: 'cand-tp-jiang',
    name: '蔣萬安',
    party: '中國國民黨',
    position: '臺北市長（爭取連任）',
    region: '臺北市',
    slogan: '市政優先，穩健前行，讓台北持續發光！',
    avatar: null,
    initials: '蔣',
    socials: {
      facebook: 'https://www.facebook.com/chiangwanan',
      instagram: 'https://www.instagram.com/wanan.chiang'
    }
  },
  {
    id: 'cand-tp-shen',
    name: '沈伯洋',
    party: '民主進步黨',
    position: '臺北市長參選人',
    region: '臺北市',
    slogan: 'SOON 順，台北順起來！打造可持續運轉的城市生態系。',
    avatar: null,
    initials: '沈',
    socials: {
      facebook: 'https://www.facebook.com/pumashen',
      threads: 'https://www.threads.net/@pumashen',
      instagram: 'https://www.instagram.com/pumashen'
    }
  },

  // --- 新北市 ---
  {
    id: 'cand-ntp-lee',
    name: '李四川',
    party: '中國國民黨',
    position: '新北市長參選人',
    region: '新北市',
    slogan: '四十年市政硬底子，把新北做得更扎實！',
    avatar: null,
    initials: '李',
    socials: {
      facebook: 'https://www.facebook.com'
    }
  },
  {
    id: 'cand-ntp-su',
    name: '蘇巧慧',
    party: '民主進步黨',
    position: '新北市長參選人',
    region: '新北市',
    slogan: '開箱新北，世代同行，新思維新首都！',
    avatar: null,
    initials: '蘇',
    socials: {
      facebook: 'https://www.facebook.com/chiaohui.su',
      instagram: 'https://www.instagram.com/su_chiaohui',
      threads: 'https://www.threads.net/@su_chiaohui'
    }
  },

  // --- 桃園市 ---
  {
    id: 'cand-ty-chang',
    name: '張善政',
    party: '中國國民黨',
    position: '桃園市長（爭取連任）',
    region: '桃園市',
    slogan: '建設看得到，科技桃園穩健起飛！',
    avatar: null,
    initials: '張',
    socials: {
      facebook: 'https://www.facebook.com/SanChengChang'
    }
  },
  {
    id: 'cand-ty-huang',
    name: '黃世杰',
    party: '民主進步黨',
    position: '桃園市長參選人',
    region: '桃園市',
    slogan: '新世代桃園隊，改變城市的活力新選擇！',
    avatar: null,
    initials: '黃',
    socials: {
      facebook: 'https://www.facebook.com'
    }
  },

  // --- 臺中市 ---
  {
    id: 'cand-tc-ho',
    name: '何欣純',
    party: '民主進步黨',
    position: '臺中市長參選人',
    region: '臺中市',
    slogan: '溫柔堅毅，行動破風，讓台中更純粹美好！',
    avatar: null,
    initials: '何',
    socials: {
      facebook: 'https://www.facebook.com/hohsinchun'
    }
  },
  {
    id: 'cand-tc-chiang',
    name: '江啟臣',
    party: '中國國民黨',
    position: '臺中市長參選人',
    region: '臺中市',
    slogan: '立足台中，放眼國際，啟動市政新速度！',
    avatar: null,
    initials: '江',
    socials: {
      facebook: 'https://www.facebook.com/JohnnyChiang1972'
    }
  },

  // --- 臺南市 ---
  {
    id: 'cand-tn-chen',
    name: '陳亭妃',
    party: '民主進步黨',
    position: '臺南市長參選人',
    region: '臺南市',
    slogan: '台南400年第一位女市長，福利六都齊！',
    avatar: null,
    initials: '陳',
    socials: {
      facebook: 'https://www.facebook.com/tingfei.tainan'
    }
  },
  {
    id: 'cand-tn-hsieh',
    name: '謝龍介',
    party: '中國國民黨',
    position: '臺南市長參選人',
    region: '臺南市',
    slogan: '藍白合力翻轉台南，我只做四年！',
    avatar: null,
    initials: '謝',
    socials: {
      facebook: 'https://www.facebook.com/longjie.tainan'
    }
  },

  // --- 高雄市 ---
  {
    id: 'cand-kh-ko',
    name: '柯志恩',
    party: '中國國民黨',
    position: '高雄市長參選人',
    region: '高雄市',
    slogan: '北高連線，溫暖承擔，給高雄新選擇！',
    avatar: null,
    initials: '柯',
    socials: {
      facebook: 'https://www.facebook.com/DrChihEnKo'
    }
  },
  {
    id: 'cand-kh-lai',
    name: '賴瑞隆',
    party: '民主進步黨',
    position: '高雄市長參選人',
    region: '高雄市',
    slogan: '挺瑞隆、拚過半，延續陳其邁五星市政！',
    avatar: null,
    initials: '賴',
    socials: {
      facebook: 'https://www.facebook.com/raylong.kh'
    }
  },

  // --- 基隆市 ---
  {
    id: 'cand-kl-hsieh',
    name: '謝國樑',
    party: '中國國民黨',
    position: '基隆市長（爭取連任）',
    region: '基隆市',
    slogan: '基隆有愛，為了下一代！',
    avatar: null,
    initials: '謝',
    socials: {
      facebook: 'https://www.facebook.com'
    }
  },
  {
    id: 'cand-kl-tung',
    name: '童子瑋',
    party: '民主進步黨',
    position: '基隆市長參選人',
    region: '基隆市',
    slogan: '新世代接棒，打造大基隆新願景！',
    avatar: null,
    initials: '童',
    socials: {
      facebook: 'https://www.facebook.com'
    }
  },

  // --- 新竹市 ---
  {
    id: 'cand-hc-kao',
    name: '高虹安',
    party: '無黨籍',
    position: '新竹市長（藍白支持連任）',
    region: '新竹市',
    slogan: '科技新竹，智慧風城，藍白合力為新竹！',
    avatar: null,
    initials: '高',
    socials: {
      facebook: 'https://www.facebook.com'
    }
  },
  {
    id: 'cand-hc-chuang',
    name: '莊競程',
    party: '民主進步黨',
    position: '新竹市長參選人',
    region: '新竹市',
    slogan: '健康永續，科技專業，大新竹再躍進！',
    avatar: null,
    initials: '莊',
    socials: {
      facebook: 'https://www.facebook.com'
    }
  },

  // --- 宜蘭縣 ---
  {
    id: 'cand-yl-wu',
    name: '吳宗憲',
    party: '中國國民黨',
    position: '宜蘭縣長參選人',
    region: '宜蘭縣',
    slogan: '議會地方攜手，拚出宜蘭新格局！',
    avatar: null,
    initials: '吳',
    socials: {
      facebook: 'https://www.facebook.com'
    }
  },

  // --- 彰化縣 ---
  {
    id: 'cand-ch-wei',
    name: '魏平政',
    party: '中國國民黨',
    position: '彰化縣長參選人',
    region: '彰化縣',
    slogan: '盧秀燕站台推薦，團結建設大彰化！',
    avatar: null,
    initials: '魏',
    socials: {
      facebook: 'https://www.facebook.com'
    }
  }
];

const EVENTS_DATA = [
  {
    "id": "evt-tp-001",
    "candidateId": "cand-tp-jiang",
    "candidateName": "蔣萬安",
    "party": "中國國民黨",
    "position": "臺北市長（爭取連任）",
    "region": "臺北市",
    "district": "信義區",
    "title": "【重大市政成果】捷運信義東延段「廣慈/奉天宮站」完工視察暨祈福",
    "type": "市政行程",
    "date": "2026-09-15",
    "time": "09:30 - 11:30",
    "locationName": "捷運廣慈/奉天宮站 1號出口廣場",
    "address": "臺北市信義區大道路與福德街口",
    "lat": 25.0392,
    "lng": 121.583,
    "description": "信義線東延段挑戰史上最難捷運工程！蔣萬安親率捷運局團隊視察完工成果，並至奉天宮參拜祈求捷運營運順利，與信義區在地里長及鄉親交流。",
    "sourceName": "聯合新聞網 UDN 專題報導（信義東延段通車視察）",
    "sourceUrl": "https://udn.com/news/story/7323/9722834",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-tp-002",
    "candidateId": "cand-tp-jiang",
    "candidateName": "蔣萬安",
    "party": "中國國民黨",
    "position": "臺北市長（爭取連任）",
    "region": "臺北市",
    "district": "信義區",
    "title": "【台北基層扎根】台北市12區基層輔選幹部誓師大會與合體造勢",
    "type": "座談會",
    "date": "2026-09-14",
    "time": "14:30 - 16:30",
    "locationName": "臺北市市政大樓 1樓大廳 / 中庭",
    "address": "臺北市信義區市府路1號",
    "lat": 25.0375,
    "lng": 121.5637,
    "description": "蔣萬安啟動9月輔選與基層請益行程，合體市議員參選人及各區里長，強調以市政建設與民意對話，打造永續共榮台北。",
    "sourceName": "聯合新聞網 UDN 報導（蔣萬安啟動輔選登記與基層誓師）",
    "sourceUrl": "https://udn.com/news/story/124652/9726621",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-tp-003",
    "candidateId": "cand-tp-jiang",
    "candidateName": "蔣萬安",
    "party": "中國國民黨",
    "position": "臺北市長（爭取連任）",
    "region": "臺北市",
    "district": "板橋區",
    "title": "【雙北跨河連線】蔣萬安合體李四川參拜慈惠宮、接雲寺與市場掃街拜票",
    "type": "掃街拜票",
    "date": "2026-09-13",
    "time": "08:30 - 11:30",
    "locationName": "板橋慈惠宮 前廣場 / 接雲寺",
    "address": "新北市板橋區府中路81號",
    "lat": 25.0089,
    "lng": 121.4582,
    "description": "雙北市長候選人合體出擊！蔣萬安跨河力挺李四川，連袂參拜板橋信仰中心接雲寺、慈惠宮，隨後深入在地傳統市場逐攤向民眾握手懇託。",
    "sourceName": "自由時報 LTN 報導（蔣萬安合體李四川板橋參拜掃街）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5563984",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-tp-004",
    "candidateId": "cand-tp-shen",
    "candidateName": "沈伯洋",
    "party": "民主進步黨",
    "position": "臺北市長參選人",
    "region": "臺北市",
    "district": "松山區",
    "title": "【南京公寓市場】深入松山傳統市場拜票與市民早市互動",
    "type": "掃街拜票",
    "date": "2026-09-06",
    "time": "上午時段（早市拜票）",
    "locationName": "南京公寓市場（南京東路五段門口）",
    "address": "臺北市松山區南京東路五段291巷",
    "lat": 25.0519,
    "lng": 121.5645,
    "description": "沈伯洋官方行程專區記錄之真實行程。走訪松山區南京公寓傳統市集，向攤商及採買市民懇託。",
    "sourceName": "沈伯洋 官方競選行程專區（2026-09-06 官方紀錄）",
    "sourceUrl": "https://puma.taipei/schedule/YovTaRdTG33utghMjSPnE",
    "status": "completed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-tp-005",
    "candidateId": "cand-tp-shen",
    "candidateName": "沈伯洋",
    "party": "民主進步黨",
    "position": "臺北市長參選人",
    "region": "臺北市",
    "district": "北投區",
    "title": "【北投石牌商城】「洋流」步行車出擊！夜市與商圈沉浸式拜票",
    "type": "掃街拜票",
    "date": "2026-09-10",
    "time": "18:30 - 20:30",
    "locationName": "石牌商城（裕民一路商圈）",
    "address": "臺北市北投區裕民一路與石牌路二段",
    "lat": 25.1165,
    "lng": 121.5178,
    "description": "沈伯洋陣營推動創新「洋流步行車」沉浸式拜票，深入石牌商城商圈與青年及在地攤商熱情互動，現場支持人潮聚集，網路關注度飆升。",
    "sourceName": "自由時報 LTN 報導（沈伯洋石牌掃街「洋流」成形）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5570158",
    "status": "completed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-tp-006",
    "candidateId": "cand-tp-shen",
    "candidateName": "沈伯洋",
    "party": "民主進步黨",
    "position": "臺北市長參選人",
    "region": "臺北市",
    "district": "大安區",
    "title": "【臨江市場】大安區深入傳統市場走訪與市民互動",
    "type": "座談會",
    "date": "2026-09-11",
    "time": "上午時段",
    "locationName": "臨江街市場（通化商圈）",
    "address": "臺北市大安區臨江街",
    "lat": 25.0305,
    "lng": 121.554,
    "description": "沈伯洋於官方行程專區發布之公開拜票行程，走訪大安區指標臨江街市集。",
    "sourceName": "沈伯洋 官方競選行程專區（2026-09-11 官方紀錄）",
    "sourceUrl": "https://puma.taipei/schedule/uNi632g1F0LfPrA2kvUsi",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-tp-007",
    "candidateId": "cand-tp-shen",
    "candidateName": "沈伯洋",
    "party": "民主進步黨",
    "position": "臺北市長參選人",
    "region": "國際/日本",
    "district": "東京",
    "title": "【訪日城市外交】啟程赴日本東京 成立日本後援會暨城市外交交流",
    "type": "掃街拜票",
    "date": "2026-09-12",
    "time": "9/12 - 9/14 訪日期間",
    "locationName": "日本東京",
    "address": "日本東京都",
    "lat": 35.6895,
    "lng": 139.6917,
    "description": "沈伯洋於9月12日啟程赴日本東京，成立沈伯洋日本後援會，並推動國會外交與智慧城市治理交流。",
    "sourceName": "FTNN新聞網 報導（沈伯洋快閃東京成立後援會行程曝光）",
    "sourceUrl": "https://www.ftnn.com.tw/news/298451",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-ntp-008",
    "candidateId": "cand-ntp-lee",
    "candidateName": "李四川",
    "party": "中國國民黨",
    "position": "新北市長參選人",
    "region": "新北市",
    "district": "板橋區",
    "title": "【新北首場萬人大造勢】40年市政硬底子，攜手侯友宜新北齊心！",
    "type": "造勢大會",
    "date": "2026-09-12",
    "time": "18:30 - 21:00",
    "locationName": "板橋第一運動場 戶外廣場",
    "address": "新北市板橋區漢生東路278號",
    "lat": 24.9996,
    "lng": 121.4674,
    "description": "李四川正式登記後首場大型造勢晚會！新北市長侯友宜親自出席站台，訴求40年扎實市政工程歷練與三環六線交通擘劃，與藍營支持者全面集結。",
    "sourceName": "聯合新聞網 UDN 報導（藍「雙北共好」造勢抗綠「雙總統級」）",
    "sourceUrl": "https://udn.com/news/story/124652/9736897",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-ntp-009",
    "candidateId": "cand-ntp-lee",
    "candidateName": "李四川",
    "party": "中國國民黨",
    "position": "新北市長參選人",
    "region": "新北市",
    "district": "板橋區",
    "title": "【雙北共好合體】台北市長蔣萬安陪同參拜接雲寺、慈惠宮與福德市場掃街",
    "type": "掃街拜票",
    "date": "2026-09-13",
    "time": "08:30 - 11:30",
    "locationName": "板橋慈惠宮 前廣場",
    "address": "新北市板橋區府中路81號",
    "lat": 25.0089,
    "lng": 121.4582,
    "description": "台北市長蔣萬安跨河力挺李四川！連袂參拜板橋信仰中心慈惠宮、接雲寺，並徒步進入板橋福德市場向市民握手懇託，營造雙北合作氣勢。",
    "sourceName": "自由時報 LTN 報導（蔣萬安合體李四川 慈惠宮參拜掃街）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5563984",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-ntp-010",
    "candidateId": "cand-ntp-lee",
    "candidateName": "李四川",
    "party": "中國國民黨",
    "position": "新北市長參選人",
    "region": "新北市",
    "district": "板橋區",
    "title": "【選戰倒數開跑】板橋競選總部完工亮相暨輔選幹部會議",
    "type": "座談會",
    "date": "2026-09-17",
    "time": "14:30 - 17:00",
    "locationName": "李四川板橋競選總部",
    "address": "新北市板橋區文化路一段",
    "lat": 25.018,
    "lng": 121.462,
    "description": "選戰倒數衝刺！李四川板橋競選總部完工亮相並對外開放，召開各行政區後援會長聯席工作會議，主打工程扎實底子與都市更新推動。",
    "sourceName": "自由時報 LTN 報導（選戰倒數 直擊李四川競總）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5569836",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-ntp-011",
    "candidateId": "cand-ntp-su",
    "candidateName": "蘇巧慧",
    "party": "民主進步黨",
    "position": "新北市長參選人",
    "region": "新北市",
    "district": "板橋區",
    "title": "【新北跨派系大集結】板橋第一運動場首場萬人造勢大會（賴清德、蔡英文力挺）",
    "type": "造勢大會",
    "date": "2026-09-14",
    "time": "18:30 - 21:00",
    "locationName": "板橋第一運動場 戶外廣場",
    "address": "新北市板橋區漢生東路278號",
    "lat": 24.9996,
    "lng": 121.4674,
    "description": "蘇巧慧首場萬人大型造勢集會！現場湧入逾兩萬名支持者，由賴清德總統、競選總部主委蔡英文親臨站台力挺，展現綠營大團結氣勢。",
    "sourceName": "聯合新聞網 UDN 報導（綠「雙總統級」站台力挺蘇巧慧）",
    "sourceUrl": "https://udn.com/news/story/124652/9736897",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-ntp-012",
    "candidateId": "cand-ntp-su",
    "candidateName": "蘇巧慧",
    "party": "民主進步黨",
    "position": "新北市長參選人",
    "region": "新北市",
    "district": "板橋區",
    "title": "【開箱新北】新北市府對面「超級F1」競選總部開放日與青年創新對談",
    "type": "座談會",
    "date": "2026-09-13",
    "time": "10:00 - 12:00",
    "locationName": "超級F1大樓 2樓 蘇巧慧競選總部",
    "address": "新北市板橋區縣民大道二段與新站路口",
    "lat": 25.0135,
    "lng": 121.464,
    "description": "設於新北市政府對面指標大樓「超級F1」，設有創意互動展區與選民交流空間，蘇巧慧親自為青年朋友導覽競選願景，主打新思維新首都。",
    "sourceName": "自由時報 LTN 報導（直擊蘇巧慧競總 月底前對外開放）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5569836",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-ntp-013",
    "candidateId": "cand-ntp-su",
    "candidateName": "蘇巧慧",
    "party": "民主進步黨",
    "position": "新北市長參選人",
    "region": "新北市",
    "district": "板橋區",
    "title": "【新北隊大出擊】蘇巧慧正式登記參選新北市長 跨派系議員全員力挺",
    "type": "掃街拜票",
    "date": "2026-09-16",
    "time": "09:00 - 11:30",
    "locationName": "新北市選舉委員會 門口廣場",
    "address": "新北市板橋區中山路一段161號",
    "lat": 25.0125,
    "lng": 121.4655,
    "description": "蘇巧慧率跨派系民進黨新北市議員參選人全員集結登記，展現新世代接棒衝勁，並宣布參與公辦電視政見辯論會。",
    "sourceName": "聯合新聞網 UDN 報導（蘇巧慧登記參選新北市長 跨派系議員集結）",
    "sourceUrl": "https://udn.com/news/story/124652/9735874",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-ty-014",
    "candidateId": "cand-ty-huang",
    "candidateName": "黃世杰",
    "party": "民主進步黨",
    "position": "桃園市長參選人",
    "region": "桃園市",
    "district": "平鎮區",
    "title": "【作伙同行迎向肆拾】副總統蕭美琴親臨站台！平鎮新勢公園老街溪健走造勢",
    "type": "造勢大會",
    "date": "2026-09-14",
    "time": "15:00 - 17:30",
    "locationName": "平鎮新勢公園 / 老街溪步道",
    "address": "桃園市平鎮區延平路一段168號",
    "lat": 24.9515,
    "lng": 121.2185,
    "description": "民進黨於平鎮新勢公園舉辦黨慶健走造勢，副總統蕭美琴親自出席為黃世杰站台，肯定黃世杰在地專業歷練，號召桃園市民作伙同行擦亮國門招牌。",
    "sourceName": "自由時報 LTN 報導（蕭美琴挺「鄰家男孩」翻轉桃園 黃世杰造勢）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5564810",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-ty-015",
    "candidateId": "cand-ty-huang",
    "candidateName": "黃世杰",
    "party": "民主進步黨",
    "position": "桃園市長參選人",
    "region": "桃園市",
    "district": "桃園區",
    "title": "【把期待交給世杰】黃世杰前往市選委會登記參選 發表「桃園13區這一封信」",
    "type": "座談會",
    "date": "2026-09-15",
    "time": "10:00 - 11:30",
    "locationName": "桃園市選舉委員會",
    "address": "桃園市桃園區成功路二段107號",
    "lat": 24.9965,
    "lng": 121.321,
    "description": "黃世杰在大陣仗議員參選人陪同下親自前往登記，並發表給全體市民的公開信，訴求打破建設停滯，帶來充滿活力的市政規劃。",
    "sourceName": "自由時報 LTN 報導（黃世杰親自登記參選 發表公開信）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5558158",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-ty-016",
    "candidateId": "cand-ty-chang",
    "candidateName": "張善政",
    "party": "中國國民黨",
    "position": "桃園市長（爭取連任）",
    "region": "桃園市",
    "district": "桃園區",
    "title": "【市政優先・穩健前行】張善政宣布全心投入重大建設 委託競總主委辦理登記",
    "type": "市政行程",
    "date": "2026-09-16",
    "time": "09:30 - 11:00",
    "locationName": "桃園市政府 市政大樓中庭",
    "address": "桃園市桃園區縣府路1號",
    "lat": 24.9932,
    "lng": 121.301,
    "description": "張善政秉持「做事比造勢重要」策略，委託競總主委黃敏恭代表登記參選，親自坐鎮市府緊盯捷運綠線北段年底通車與婦幼政策成果。",
    "sourceName": "自由時報 LTN 報導（張善政市政優先 委託總部主委登記）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5558158",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-tc-017",
    "candidateId": "cand-tc-ho",
    "candidateName": "何欣純",
    "party": "民主進步黨",
    "position": "臺中市長參選人",
    "region": "臺中市",
    "district": "南屯區",
    "title": "【小英前總統親臨授證】蔡英文出任何欣純競選總部榮譽主委 勉勵市政「緊緊緊」",
    "type": "造勢大會",
    "date": "2026-09-13",
    "time": "14:30 - 17:00",
    "locationName": "何欣純競選總部",
    "address": "臺中市南屯區五權西路二段1127號",
    "lat": 24.1376,
    "lng": 120.6272,
    "description": "蔡英文前總統親臨何欣純競選總部為團隊授證，以陳其邁高雄經驗勉勵何欣純面對台中轉型也要「緊緊緊」且鍥而不捨，場面溫馨熱烈。",
    "sourceName": "聯合新聞網 UDN 報導（蔡英文接何欣純競總榮譽主委 勉勵緊緊緊）",
    "sourceUrl": "https://udn.com/news/story/124652/9741577",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-tc-018",
    "candidateId": "cand-tc-ho",
    "candidateName": "何欣純",
    "party": "民主進步黨",
    "position": "臺中市長參選人",
    "region": "臺中市",
    "district": "清水區",
    "title": "【4321海線大進擊】清水第一市場深入掃街 發表海空雙港觀光新政見",
    "type": "掃街拜票",
    "date": "2026-09-16",
    "time": "08:30 - 11:00",
    "locationName": "清水第一公有零售市場",
    "address": "臺中市清水區新興路",
    "lat": 24.269,
    "lng": 120.57,
    "description": "何欣純勤走海線基層，至清水傳統市場向攤商握手請益，主打「4321海線大進擊」，結合台中港與清泉崗機場打造海空雙港商貿聚落。",
    "sourceName": "聯合新聞網 UDN 報導（何欣純清水市場拜票談海線願景）",
    "sourceUrl": "https://udn.com/news/story/124652/9748457",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-tc-019",
    "candidateId": "cand-tc-ho",
    "candidateName": "何欣純",
    "party": "民主進步黨",
    "position": "臺中市長參選人",
    "region": "臺中市",
    "district": "西區",
    "title": "【團結台中隊】何欣純正式登記參選台中市長 蔡其昌任主委合體誓師",
    "type": "座談會",
    "date": "2026-09-14",
    "time": "10:00 - 11:30",
    "locationName": "臺中市選舉委員會",
    "address": "臺中市西區光明路",
    "lat": 24.14,
    "lng": 120.665,
    "description": "何欣純正式完成參選登記，宣布蔡其昌出任競選總部主委，展現全黨跨派系整合戰力，鎖定民調黃金交叉。",
    "sourceName": "自由時報 LTN 報導（何欣純登記參選 邀小英任榮譽主委、蔡其昌任主委）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5560395",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-tc-020",
    "candidateId": "cand-tc-chiang",
    "candidateName": "江啟臣",
    "party": "中國國民黨",
    "position": "臺中市長參選人",
    "region": "臺中市",
    "district": "東勢區",
    "title": "【越挺我越拚命】江啟臣山城大型造勢大會 凝聚山線鄉親催票拚全壘打",
    "type": "造勢大會",
    "date": "2026-09-19",
    "time": "18:30 - 21:00",
    "locationName": "東勢客家文化園區 廣場",
    "address": "臺中市東勢區中山路1號",
    "lat": 24.2585,
    "lng": 120.829,
    "description": "江啟臣回到山城大本營舉辦盛大造勢活動，強調在地深耕與東勢、新社、石岡交通網絡升級，呼籲鄉親團結全力催票。",
    "sourceName": "聯合新聞網 UDN 報導（江啟臣山城造勢催票拚全壘打）",
    "sourceUrl": "https://udn.com/news/story/124652/9745903",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-tn-021",
    "candidateId": "cand-tn-hsieh",
    "candidateName": "謝龍介",
    "party": "中國國民黨",
    "position": "臺南市長參選人",
    "region": "臺南市",
    "district": "安平區",
    "title": "【藍白合作翻轉大台南】謝龍介率先完成市長參選登記 號召在野團結為台南贏一次",
    "type": "掃街拜票",
    "date": "2026-09-14",
    "time": "09:30 - 11:30",
    "locationName": "臺南市選舉委員會 門口廣場",
    "address": "臺南市安平區中華西路二段315號",
    "lat": 22.992,
    "lng": 120.185,
    "description": "謝龍介率先前往選委會登記參選，在國民黨與民眾黨市議員參選人簇擁下高呼「讓台南贏一次」，宣示在野大整合決心。",
    "sourceName": "聯合新聞網 UDN 報導（謝龍介率先登記參選台南市長 喊話藍白合作）",
    "sourceUrl": "https://udn.com/news/story/124652/9727456",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-tn-022",
    "candidateId": "cand-tn-hsieh",
    "candidateName": "謝龍介",
    "party": "中國國民黨",
    "position": "臺南市長參選人",
    "region": "臺南市",
    "district": "中西區",
    "title": "【只做一屆・大刀闊斧】謝龍介藍白整合座談 發表生孩供房「最強婚育宅」政策",
    "type": "座談會",
    "date": "2026-09-17",
    "time": "19:00 - 21:00",
    "locationName": "祀典武廟 廟埕廣場",
    "address": "臺南市中西區永福路二段229號",
    "lat": 22.9968,
    "lng": 120.2018,
    "description": "謝龍介在武廟前舉辦基層座談，重申承諾「只做四年，沒有連任包袱」，大刀闊斧推動婚育宅與生育津貼加碼。",
    "sourceName": "聯合新聞網 UDN 報導（藍白整合挺謝龍介「只做1屆 要大刀闊斧改革」）",
    "sourceUrl": "https://udn.com/news/story/124652/9728259",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-tn-023",
    "candidateId": "cand-tn-chen",
    "candidateName": "陳亭妃",
    "party": "民主進步黨",
    "position": "臺南市長參選人",
    "region": "臺南市",
    "district": "安平區",
    "title": "【台南400年首位女市長】陳亭妃在黃偉哲市長陪同下正式登記參選",
    "type": "掃街拜票",
    "date": "2026-09-15",
    "time": "10:00 - 12:00",
    "locationName": "臺南市選舉委員會",
    "address": "臺南市安平區中華西路二段315號",
    "lat": 22.992,
    "lng": 120.185,
    "description": "陳亭妃由現任市長黃偉哲、民進黨市黨部主委及多位議員參選人陪同正式登記，展現綠營執政延續與跨世代團結。",
    "sourceName": "聯合新聞網 UDN 報導（陳亭妃登記參選台南市長 黃偉哲任競總主委）",
    "sourceUrl": "https://udn.com/news/story/124652/9736431",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-tn-024",
    "candidateId": "cand-tn-chen",
    "candidateName": "陳亭妃",
    "party": "民主進步黨",
    "position": "臺南市長參選人",
    "region": "臺南市",
    "district": "永康區",
    "title": "【2026、2028都要贏】陳亭妃與市黨部召開輔選聯席會議 確立永康競選總部基地",
    "type": "座談會",
    "date": "2026-09-18",
    "time": "14:30 - 16:30",
    "locationName": "民進黨臺南市黨部 / 永康競選總部預定地",
    "address": "臺南市永康區中華路",
    "lat": 23.015,
    "lng": 120.235,
    "description": "陳亭妃競選總部敲定設於人口第一大區永康，團隊由賴清德擔任名譽主委、黃偉哲任主委，全力推進農業、半導體AI、醫療「科技三軸」願景。",
    "sourceName": "聯合新聞網 UDN 報導（陳亭妃與市黨部開輔選會議 競總設永康）",
    "sourceUrl": "https://udn.com/news/story/124652/9675087",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-kh-025",
    "candidateId": "cand-kh-ko",
    "candidateName": "柯志恩",
    "party": "中國國民黨",
    "position": "高雄市長參選人",
    "region": "高雄市",
    "district": "鼓山區",
    "title": "【南高雄後援會成立】林皇宮千人造勢大會！許淑華力挺、柯志恩宣示翻轉高雄",
    "type": "造勢大會",
    "date": "2026-09-13",
    "time": "14:00 - 17:00",
    "locationName": "高雄林皇宮 5樓全壽廳",
    "address": "高雄市鼓山區博愛二路99號",
    "lat": 22.657,
    "lng": 120.3035,
    "description": "柯志恩成立南高雄競選後援會，南投縣長許淑華南下站台力挺，現場湧入上千支持者，柯志恩發表205兵工廠與中央公園2.0新願景。",
    "sourceName": "自由時報 LTN 報導（柯志恩南高雄後援會成立 許淑華站台力挺）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5564209",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-kh-026",
    "candidateId": "cand-kh-ko",
    "candidateName": "柯志恩",
    "party": "中國國民黨",
    "position": "高雄市長參選人",
    "region": "高雄市",
    "district": "鳳山區",
    "title": "【穩穩接住高雄】鳳山廟口開講「廟口那卡西」巡迴 宣示接棒高雄新世代",
    "type": "座談會",
    "date": "2026-09-19",
    "time": "18:30 - 21:00",
    "locationName": "鳳山雙慈殿 廟前廣場",
    "address": "高雄市鳳山區三民路287號",
    "lat": 22.6245,
    "lng": 120.3585,
    "description": "柯志恩持續推動「廟口那卡西」深度基層對話，於鳳山熱門宮廟前與民眾歡聚，宣示要以女性堅韌與專業能力穩穩接住高雄市政。",
    "sourceName": "聯合新聞網 UDN 報導（柯志恩喊接棒高雄：我可以穩穩接住）",
    "sourceUrl": "https://udn.com/news/story/124652/9736698",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-kh-027",
    "candidateId": "cand-kh-lai",
    "candidateName": "賴瑞隆",
    "party": "民主進步黨",
    "position": "高雄市長參選人",
    "region": "高雄市",
    "district": "苓雅區",
    "title": "【選對人才能走對的路】陳其邁市長親自陪同賴瑞隆登記參選高雄市長",
    "type": "掃街拜票",
    "date": "2026-09-14",
    "time": "09:00 - 11:30",
    "locationName": "高雄市選舉委員會 門口廣場",
    "address": "高雄市苓雅區憲政路229號",
    "lat": 22.636,
    "lng": 120.3275,
    "description": "現任市長陳其邁出任競選總部主委，親自陪同賴瑞隆完成市長登記，強調高雄轉型關鍵時刻「選對人才能走對的路」。",
    "sourceName": "自由時報 LTN 報導（陳其邁陪賴瑞隆登記參選市長：高雄人最有經驗）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5560283",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-kh-028",
    "candidateId": "cand-kh-lai",
    "candidateName": "賴瑞隆",
    "party": "民主進步黨",
    "position": "高雄市長參選人",
    "region": "高雄市",
    "district": "左營區",
    "title": "【九宮格陸戰啟動】左營博愛路口早晨向通勤市民揮手 規劃全市各區後援集會",
    "type": "掃街拜票",
    "date": "2026-09-17",
    "time": "07:30 - 09:30",
    "locationName": "左營區博愛三路與曾子路口",
    "address": "高雄市左營區博愛三路與曾子路口",
    "lat": 22.6841,
    "lng": 120.309,
    "description": "賴瑞隆競選團隊啟動「九宮格戰法」，結合全市各區黨公職與社團，於尖峰路口向市民致意，並緊鑼密鼓籌辦大型造勢大會。",
    "sourceName": "自由時報 LTN 報導（高雄戰情》賴瑞隆發動「九宮格」陸戰 衝刺投票率）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5538055",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-kl-029",
    "candidateId": "cand-kl-hsieh",
    "candidateName": "謝國樑",
    "party": "中國國民黨",
    "position": "基隆市長（爭取連任）",
    "region": "基隆市",
    "district": "中正區",
    "title": "【基隆有愛，為了下一代】謝國樑發表連任主軸 與青年團隊座談延續市政建設",
    "type": "座談會",
    "date": "2026-09-18",
    "time": "19:00 - 21:00",
    "locationName": "基隆文化中心 大廳",
    "address": "基隆市中正區信一路181號",
    "lat": 25.131,
    "lng": 121.745,
    "description": "謝國樑宣布以「基隆有愛，為了下一代」為主軸爭取連任，強調行人友善示範區成效與室內兒童樂園建設，向基層青年與商圈代表說明第二任藍圖。",
    "sourceName": "聯合新聞網 UDN 報導（謝國樑連任選戰主軸「基隆有愛，為了下一代」）",
    "sourceUrl": "https://udn.com/news/story/124652/9727449",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-yl-030",
    "candidateId": "cand-yl-wu",
    "candidateName": "吳宗憲",
    "party": "中國國民黨",
    "position": "宜蘭縣長參選人",
    "region": "宜蘭縣",
    "district": "宜蘭市",
    "title": "【宜蘭藍白整合共推】吳宗憲登記參選宜蘭縣長 議長張勝德、陳琬惠合體力挺",
    "type": "掃街拜票",
    "date": "2026-09-15",
    "time": "09:00 - 11:00",
    "locationName": "宜蘭縣選舉委員會 門口",
    "address": "宜蘭縣宜蘭市神農路二段100號",
    "lat": 24.751,
    "lng": 121.751,
    "description": "宜蘭藍白正式合體！國民黨與民眾黨共同推舉吳宗憲參選宜蘭縣長，議長張勝德與民眾黨陳琬惠陪同登記，宣示打造「利他」新縣政。",
    "sourceName": "自由時報 LTN 報導（吳宗憲登記參選宜蘭縣長 議長張勝德、陳琬惠陪同）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5556219",
    "status": "confirmed",
    "verified": true,
    "isPopular": true
  },
  {
    "id": "evt-ch-031",
    "candidateId": "cand-ch-wei",
    "candidateName": "魏平政",
    "party": "中國國民黨",
    "position": "彰化縣長參選人",
    "region": "彰化縣",
    "district": "彰化市",
    "title": "【彰化縣長選戰】魏平政正式完成參選登記 凝聚藍營基層與地方農漁會幹部",
    "type": "掃街拜票",
    "date": "2026-09-16",
    "time": "10:00 - 12:00",
    "locationName": "彰化縣選舉委員會",
    "address": "彰化縣彰化市中山路二段416號",
    "lat": 24.0755,
    "lng": 120.5441,
    "description": "魏平政前往彰化縣選委會正式完成登記，展現接棒王惠美執政決心，主打中彰投軌道交通串聯與高科技精密機械廊帶發展。",
    "sourceName": "自由時報 LTN 報導（魏平政參選登記 藍營整合與地方動態）",
    "sourceUrl": "https://news.ltn.com.tw/news/politics/breakingnews/5561646",
    "status": "confirmed",
    "verified": true
  },
  {
    "id": "evt-ch-032",
    "candidateId": "cand-ch-wei",
    "candidateName": "魏平政",
    "party": "中國國民黨",
    "position": "彰化縣長參選人",
    "region": "彰化縣",
    "district": "彰化市",
    "title": "【藍營彰化大集結】彰化縣黨部召開全縣輔選聯席會議 魏平政力拚建設大彰化",
    "type": "座談會",
    "date": "2026-09-19",
    "time": "14:30 - 17:00",
    "locationName": "國民黨彰化縣黨部 大禮堂",
    "address": "彰化縣彰化市三民路",
    "lat": 24.081,
    "lng": 120.542,
    "description": "國民黨彰化縣黨部召集各鄉鎮黨公職舉行全縣輔選會議，全力輔選魏平政，整合地方基層後援戰力迎接選戰倒數。",
    "sourceName": "聯合新聞網 UDN 報導（魏平政藍彰化縣黨部整合輔選會議）",
    "sourceUrl": "https://udn.com/news/story/124652/9748449",
    "status": "confirmed",
    "verified": true
  }
];
